# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8431850d04582b591710411bf10a6b24a867a265de226896fd83a843053103f4092d78b15a216f3db67e0158d149c8884bb7f086f30b935aba345168bb4b3dbc

test:
  secret_key_base: 5518c8e56fbc5da05ded5b2e1110cc417ae23ea34901f4aca91389adacf61ccf6d12746da0d696133570d708baaf292e7dfb5f3d1d415e62b12b84dbfe722550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
